import fs from "node:fs";
import path from "node:path";

/**
 * Resolves a post's card image, shared by every place that lists posts (blog
 * index, home "Useful reads", related reading at the foot of a post).
 *
 * The directory is read once at module load, so a card rendered after the
 * server started will not be picked up until it restarts. That is fine in
 * production, where the build reads it fresh, and it is the same trade the blog
 * index already made: one readdir instead of a stat on every card render.
 *
 * Cards are generated by scripts/thumbs (see that README). Anything without one
 * falls back to a real brand photo rather than a broken image.
 */
const BLOG_IMAGE_DIR = path.join(process.cwd(), "public", "blog");

export const DEFAULT_POST_IMAGE = "/simon-jacobs-event.webp";

const HAS_IMAGE: Set<string> = (() => {
  try {
    return new Set(
      fs
        .readdirSync(BLOG_IMAGE_DIR)
        .filter((f) => f.endsWith(".webp"))
        .map((f) => f.replace(/\.webp$/, "")),
    );
  } catch {
    return new Set<string>();
  }
})();

export function postImage(slug: string): string {
  return HAS_IMAGE.has(slug) ? `/blog/${slug}.webp` : DEFAULT_POST_IMAGE;
}
