/**
 * Writes scripts/thumbs/assets/inline-data.js, the bridge between cards.mjs
 * and template.html.
 *
 * template.html is opened over file:// (both by Chrome headless when
 * rendering and by a human previewing the whole set). Over file:// a page
 * cannot fetch() a sibling file and cannot import an ES module, but it CAN
 * load a plain <script src="...">. So the card data and the cutout are
 * baked into a classic script that sets window.__THUMBS__.
 *
 * Keeping cards.mjs as the only place card copy lives means the template can
 * never drift out of sync with it.
 *
 * Run directly, or let render.mjs / preview call it.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { cards } from "./cards.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const assets = path.join(here, "assets");

async function webpDataUri(pipeline) {
  const buf = await pipeline.webp({ quality: 88, alphaQuality: 100 }).toBuffer();
  return { uri: `data:image/webp;base64,${buf.toString("base64")}`, bytes: buf.length };
}

async function main() {
  // Default is the studio headshot cut out by cutout.mjs. THUMB_CUTOUT swaps it
  // for another file in assets/ without touching this script.
  const cutoutPath = path.join(assets, process.env.THUMB_CUTOUT || "simon-suit-cutout.png");
  const cropPath = path.join(assets, "simon-crop.jpg");

  // The cutout only ever renders at roughly 1000px wide on a 2400px card, so
  // 1400px is plenty and keeps the inlined payload small.
  const cutout = await webpDataUri(sharp(cutoutPath).resize({ width: 1400 }));

  // Heavily blurred copy of the source crop, used as a low-opacity depth
  // layer behind the gradient. Tiny on purpose: it is blurred to mush anyway.
  let backdrop = { uri: "", bytes: 0 };
  try {
    backdrop = await webpDataUri(
      sharp(cropPath).resize({ width: 220 }).blur(18).modulate({ saturation: 0.7 }),
    );
  } catch {
    console.warn("! simon-crop.jpg missing, skipping the blurred backdrop layer");
  }

  const out = [
    "/* GENERATED by scripts/thumbs/build-data.mjs. Do not edit by hand. */",
    "window.__THUMBS__ = {",
    `  cards: ${JSON.stringify(cards, null, 2).replace(/\n/g, "\n  ")},`,
    `  simon: ${JSON.stringify(cutout.uri)},`,
    `  backdrop: ${JSON.stringify(backdrop.uri)}`,
    "};",
    "",
  ].join("\n");

  const target = path.join(assets, "inline-data.js");
  await fs.writeFile(target, out, "utf8");

  const kb = (n) => `${(n / 1024).toFixed(0)}KB`;
  console.log(
    `inline-data.js written: ${cards.length} cards, cutout ${kb(cutout.bytes)}, backdrop ${kb(backdrop.bytes)}, total ${kb(Buffer.byteLength(out))}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
